#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)
STOW_DIR="${DOTFILES_ROOT}/stow"

set -e

echo ''

info() {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user() {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success() {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

require_util() {
    type "$1" > /dev/null 2>&1 || command -v "$1" > /dev/null 2>&1 ||
        fail "You do not have '$1' installed"
}

check_requirements() {
    require_util stow
}

setup_gitconfig() {
    if ! [[ -f "${STOW_DIR}/git/.gitconfig" ]]
    then
        info 'setup gitconfig'

        GIT_CREDENTIAL='cache'
        if [[ "$(uname -s)" == "Darwin" ]]
        then
          GIT_CREDENTIAL='osxkeychain'
        fi

        user ' - What is your github author name?'
        read -e GIT_AUTHOR_NAME
        user ' - What is your github author email?'
        read -e GIT_AUTHOR_EMAIL

        sed -e "s/AUTHORNAME/${GIT_AUTHOR_NAME}/g" \
        -e "s/AUTHOREMAIL/${GIT_AUTHOR_EMAIL}/g" \
        -e "s/GIT_CREDENTIAL_HELPER/${GIT_CREDENTIAL}/g" \
      "${STOW_DIR}/git/.gitconfig.template" > "${STOW_DIR}/git/.gitconfig"

    success 'gitconfig'
  fi
}

link_stow() {
    local SRC="${1}"
    local DIR="$(dirname ${SRC})"
    local PACKAGE="$(basename ${SRC})"
    stow -d "${DIR}" -t "${HOME}" -S "${PACKAGE}" || fail "failed to stow ${SRC}"
    success "stowed ${SRC}"
}


install_dotfiles() {
    info 'installing dotfiles'

    for SRC in $(find "${STOW_DIR}" -maxdepth 1 -type d -not -path "*/stow")
    do
      link_stow "${SRC}"
    done
}

check_requirements
setup_gitconfig
install_dotfiles

echo ''
echo '  All installed!'
